//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Botter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Botter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0:4286545791
        ///0,1:4286216574
        ///0,2:4285952638
        ///0,3:4285754494
        ///0,4:4285556606
        ///0,5:4285490303
        ///0,6:4285358463
        ///0,7:4285226366
        ///0,8:4285160062
        ///0,9:4285093758
        ///0,10:4285027711
        ///0,11:4285027200
        ///0,12:4285026945
        ///0,13:4284961153
        ///0,14:4284895361
        ///0,15:4284829568
        ///0,16:4284763519
        ///0,17:4284763007
        ///0,18:4284828031
        ///0,19:4284827521
        ///0,20:4284827010
        ///0,21:4284892547
        ///0,22:4284892548
        ///0,23:4284958084
        ///0,24:4284958085
        ///0,25:4284958086
        ///0,26:4284958088
        ///0,27:4284957833
        ///0,28:4284892296
        ///0,29:4284892551
        ///0,30:4284893061
        ///0,31:4284893314
        ///0,32:42848 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swf_values_100 {
            get {
                return ResourceManager.GetString("swf_values_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0:4286545791
        ///0,1:4286216835
        ///0,2:4285953925
        ///0,3:4285822087
        ///0,4:4285690761
        ///0,5:4285559178
        ///0,6:4285493388
        ///0,7:4285361805
        ///0,8:4285230479
        ///0,9:4285164688
        ///0,10:4285099153
        ///0,11:4285164689
        ///0,12:4285164688
        ///0,13:4285164688
        ///0,14:4285229968
        ///0,15:4285229968
        ///0,16:4285164434
        ///0,17:4285033107
        ///0,18:4284967573
        ///0,19:4284836502
        ///0,20:4284836759
        ///0,21:4284902551
        ///0,22:4285034134
        ///0,23:4285165461
        ///0,24:4285230995
        ///0,25:4285296274
        ///0,26:4285230480
        ///0,27:4285230224
        ///0,28:4285230224
        ///0,29:4285296016
        ///0,30:4285427344
        ///0,31:4285492880
        ///0,32:42854 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swf_values_101 {
            get {
                return ResourceManager.GetString("swf_values_101", resourceCulture);
            }
        }
    }
}
